name: Test Script

on:
  push:
    branches:
      - main
      - test-branch  # Specify the branches to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VAR1: "Hello"
    steps:
      - name: Set up dynamic environment variable
        run: echo "DYNAMIC_VAR=${{ env.VAR1 }} World" >> $GITHUB_ENV
      
      - name: Use the dynamic environment variable
        run: echo $DYNAMIC_VAR
