name: Test Script

on:
  push:
    branches:
      - main
      - test-branch  # Specify the branches to trigger the workflow

jobs:
  example_job:
    runs-on: ubuntu-latest
    env:
      VAR_ONE: "value1"
    steps:
      - name: Step with variables
        run: |
          VAR_TWO="This will work: $VAR_ONE"  # Expands during execution
          echo "VAR_TWO=$VAR_TWO" >> $GITHUB_ENV
    
      - name: Print VAR_TWO
        run: |
            echo "VAR_TWO is: $VAR_TWO"

