name: Test Script

on:
  push:
    branches:
      - main
      - test-branch  # Specify the branches to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VAR1: "Hello"
    steps:
      - name: Use the environment variable in a step
        env:
          VAR2: "DYNAMIC ${VAR1}"
        run: echo $VAR2

